force-app/main/default/objects/RSS_Feed_Config__mdt/RSS_Feed_Config__mdt.object-meta.xml
<CustomObject>
    <label>RSS Feed Config</label>
    <pluralLabel>RSS Feed Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/From_Name_And_Email__c.field-meta.xml
<CustomField>
    <fullName>From_Name_And_Email__c</fullName>
    <label>From Name And Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/RSS_Feed_URL__c.field-meta.xml
<CustomField>
    <fullName>RSS_Feed_URL__c</fullName>
    <label>RSS Feed URL</label>
    <length>130768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/To_Mail__c.field-meta.xml
<CustomField>
    <fullName>To_Mail__c</fullName>
    <label>To Mail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RSSFeedUtilTest.cls
@isTest
public with sharing class RSSFeedUtilTest {
    @isTest
    static void testGetAllFeedConfigWithNoCMDTRecords() {

        Test.startTest();
        try{
            List<RSS_Feed_Config__mdt> result = RSSFeedUtil.getAllFeedConfigCMDT();
        }
        catch(Exception ex){
            System.assert(ex instanceof RSSFeedException, 'RSSFeedException should be thrown');
        }
        Test.stopTest();
    }

    @isTest
    static void testGetRecByDeveloperNameFeedConfigWithNoCMDTRecord() {

        Test.startTest();
        try{
            RSS_Feed_Config__mdt result = RSSFeedUtil.getFeedConfigByDeveloperName('test');
        }
        catch(Exception ex){
            System.assert(ex instanceof RSSFeedException, 'RSSFeedException should be thrown');
        }
        Test.stopTest();
    }

    @isTest
    static void testGetAllFeedConfigWithCMDTRecords() {


        Test.startTest();
        RSS_Feed_Config__mdt simulatedFeedConfig = new RSS_Feed_Config__mdt(
            DeveloperName = 'TestCategory',
            Label = 'Test Category',
            RSS_Feed_URL__c = 'https://example.com/test-rss-feed',
            To_Mail__c = 'test@to.com',
            From_Name_And_Email__c = 'Test Name <test@from.com>'

        );
        RSSFeedUtil.feedConfig = simulatedFeedConfig;
        RSSFeedUtil.feedConfigList = new List<RSS_Feed_Config__mdt>{simulatedFeedConfig};
        List<RSS_Feed_Config__mdt> result;
        result = RSSFeedUtil.getAllFeedConfigCMDT();
        System.assert(result.size() > 0, 'No RSS Feed Configs Found');
        Test.stopTest();
    }

    @isTest
    static void testGetRecByDeveloperNameFeedConfigWithCMDTRecord() {

        Test.startTest();
        RSS_Feed_Config__mdt simulatedFeedConfig = new RSS_Feed_Config__mdt(
            DeveloperName = 'TestCategory',
            Label = 'Test Category',
            RSS_Feed_URL__c = 'https://example.com/test-rss-feed',
            To_Mail__c = 'test@to.com',
            From_Name_And_Email__c = 'Test Name <test@from.com>'

        );
        RSSFeedUtil.feedConfig = simulatedFeedConfig;
        RSS_Feed_Config__mdt result = RSSFeedUtil.getFeedConfigByDeveloperName('test');
        System.assert(result != null, 'No RSS Feed Config Found');
        Test.stopTest();
    }

}