force-app/main/default/objects/RSS_Feed_Config__mdt/RSS_Feed_Config__mdt.object-meta.xml
<CustomObject>
    <label>RSS Feed Config</label>
    <pluralLabel>RSS Feed Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/From_Name_And_Email__c.field-meta.xml
<CustomField>
    <fullName>From_Name_And_Email__c</fullName>
    <label>From Name And Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/Order_Of_Processing__c.field-meta.xml
<CustomField>
    <fullName>Order_Of_Processing__c</fullName>
    <label>Order Of Processing</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/RSS_Feed_URL__c.field-meta.xml
<CustomField>
    <fullName>RSS_Feed_URL__c</fullName>
    <label>RSS Feed URL</label>
    <length>130768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/To_Mail__c.field-meta.xml
<CustomField>
    <fullName>To_Mail__c</fullName>
    <label>To Mail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RSSFeedUtil.cls
public with sharing class RSSFeedUtil {
    @TestVisible public static List<RSS_Feed_Config__mdt> feedConfigList;
    @TestVisible public static RSS_Feed_Config__mdt feedConfig;

    
    public static List<RSS_Feed_Config__mdt> getAllFeedConfigCMDT(){
        if(feedConfigList != null){
            return feedConfigList;
        }
        else{
            List<RSS_Feed_Config__mdt> feedConfigList = [SELECT Id, Label, DeveloperName, From_Name_And_Email__c,
                Order_Of_Processing__c, RSS_Feed_URL__c, To_Mail__c FROM RSS_Feed_Config__mdt ORDER BY Order_Of_Processing__c ASC];
            if(feedConfigList == null || feedConfigList.size() == 0){
                throw new RSSFeedException('No RSS Feed Configs Found');
            }
            return feedConfigList;
        }

    }

    public static RSS_Feed_Config__mdt getFeedConfigByDeveloperName(String developerName){
        if(feedConfig != null){
            return feedConfig;
        }
        else{
            List<RSS_Feed_Config__mdt> feedConfigList = [SELECT Id, Label, DeveloperName, From_Name_And_Email__c,
                Order_Of_Processing__c, RSS_Feed_URL__c, To_Mail__c FROM RSS_Feed_Config__mdt WHERE DeveloperName = :developerName];
            if(feedConfigList == null || feedConfigList.size() == 0){
                throw new RSSFeedException('No RSS Feed Config Found');
            }
            return feedConfigList[0];
        }

    }
}