force-app/main/default/objects/RSS_Feed_Config__mdt/RSS_Feed_Config__mdt.object-meta.xml
<CustomObject>
    <label>RSS Feed Config</label>
    <pluralLabel>RSS Feed Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/From_Name_And_Email__c.field-meta.xml
<CustomField>
    <fullName>From_Name_And_Email__c</fullName>
    <label>From Name And Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/RSS_Feed_URL__c.field-meta.xml
<CustomField>
    <fullName>RSS_Feed_URL__c</fullName>
    <label>RSS Feed URL</label>
    <length>130768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/To_Mail__c.field-meta.xml
<CustomField>
    <fullName>To_Mail__c</fullName>
    <label>To Mail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/RSS_Feed_Entry__c.object-meta.xml
<CustomObject>
    <label>RSS Feed Entry</label>
    <nameField>
        <displayFormat>RFE-{000000}</displayFormat>
        <label>RSS Feed Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RSS Feed Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Entry_GUID__c.field-meta.xml
<CustomField>
    <fullName>Entry_GUID__c</fullName>
    <externalId>true</externalId>
    <label>Entry GUID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Entry_Link__c.field-meta.xml
<CustomField>
    <fullName>Entry_Link__c</fullName>
    <label>Entry Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Feed_Category__c.field-meta.xml
<CustomField>
    <fullName>Feed_Category__c</fullName>
    <label>Feed Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Feed_Entry_Description__c.field-meta.xml
<CustomField>
    <fullName>Feed_Entry_Description__c</fullName>
    <label>Feed Entry Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Feed_Entry_Title__c.field-meta.xml
<CustomField>
    <fullName>Feed_Entry_Title__c</fullName>
    <label>Feed Entry Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Publication_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Publication_Date_Time__c</fullName>
    <label>Publication Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Run_Config__c/RSS_Feed_Run_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RSS Feed Run Config</label>
</CustomObject>

force-app/main/default/objects/RSS_Feed_Run_Config__c/fields/Last_Processed_Feed_Category__c.field-meta.xml
<CustomField>
    <fullName>Last_Processed_Feed_Category__c</fullName>
    <label>Last Processed Feed Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeleteOldFeedEntriesBatchTest.cls
@isTest
public class DeleteOldFeedEntriesBatchTest {

    @isTest
    static void testDeleteOldFeedEntriesBatch() {
        RSS_Feed_Run_Config__c customSettingRecord = new RSS_Feed_Run_Config__c();
        customSettingRecord.Last_Processed_Feed_Category__c = 'category';
        insert customSettingRecord;

        RSS_Feed_Config__mdt simulatedFeedConfig = new RSS_Feed_Config__mdt(
            DeveloperName = 'TestCategory',
            Label = 'Test Category',
            RSS_Feed_URL__c = 'https://example.com/test-rss-feed',
            To_Mail__c = 'test@to.com',
            From_Name_And_Email__c = 'Test Name <test@from.com>'

        );
        RSSFeedUtil.feedConfig = simulatedFeedConfig;
        RSSFeedUtil.feedConfigList = new List<RSS_Feed_Config__mdt>{simulatedFeedConfig};

        // Insert test data - Feed entries older than one week
        List<RSS_Feed_Entry__c> feedEntries = new List<RSS_Feed_Entry__c>();
        for (Integer i = 0; i < 10; i++) {
            RSS_Feed_Entry__c feedEntry = new RSS_Feed_Entry__c(
                Feed_Entry_Title__c = 'Test Entry ' + i,
                Publication_Date_Time__c = System.now().addDays(-8),
                Entry_Link__c = 'https://example.com/test-entry-' + i,
                Feed_Category__c = 'TestCategory',
                Feed_Entry_Description__c = 'Test Description ' + i,
                Entry_GUID__c = '123456'+i
            );
            feedEntries.add(feedEntry);
        }
        insert feedEntries;
        (new DeleteOldFeedEntriesBatch()).start(null);
        (new DeleteOldFeedEntriesBatch()).finish(null);
        (new DeleteOldFeedEntriesBatch()).execute(null, feedEntries);

        // Verify that the records were deleted
        List<RSS_Feed_Entry__c> deletedFeedEntries = [SELECT Id FROM RSS_Feed_Entry__c WHERE CreatedDate < :System.today().addDays(-7)];
        System.assertEquals(0, deletedFeedEntries.size(), 'Feed entries should be deleted.');

    }
}