force-app/main/default/objects/RSS_Feed_Config__mdt/RSS_Feed_Config__mdt.object-meta.xml
<CustomObject>
    <label>RSS Feed Config</label>
    <pluralLabel>RSS Feed Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/From_Name_And_Email__c.field-meta.xml
<CustomField>
    <fullName>From_Name_And_Email__c</fullName>
    <label>From Name And Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/RSS_Feed_URL__c.field-meta.xml
<CustomField>
    <fullName>RSS_Feed_URL__c</fullName>
    <label>RSS Feed URL</label>
    <length>130768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Config__mdt/fields/To_Mail__c.field-meta.xml
<CustomField>
    <fullName>To_Mail__c</fullName>
    <label>To Mail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/RSS_Feed_Entry__c.object-meta.xml
<CustomObject>
    <label>RSS Feed Entry</label>
    <nameField>
        <displayFormat>RFE-{000000}</displayFormat>
        <label>RSS Feed Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RSS Feed Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Email_Send_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Send_Status__c</fullName>
    <defaultValue>&apos;New&apos;</defaultValue>
    <label>Email Send Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Entry_GUID__c.field-meta.xml
<CustomField>
    <fullName>Entry_GUID__c</fullName>
    <externalId>true</externalId>
    <label>Entry GUID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Entry_Link__c.field-meta.xml
<CustomField>
    <fullName>Entry_Link__c</fullName>
    <label>Entry Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Feed_Category__c.field-meta.xml
<CustomField>
    <fullName>Feed_Category__c</fullName>
    <label>Feed Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Feed_Entry_Description__c.field-meta.xml
<CustomField>
    <fullName>Feed_Entry_Description__c</fullName>
    <label>Feed Entry Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Feed_Entry_Title__c.field-meta.xml
<CustomField>
    <fullName>Feed_Entry_Title__c</fullName>
    <label>Feed Entry Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Entry__c/fields/Publication_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Publication_Date_Time__c</fullName>
    <label>Publication Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Run_Config__c/RSS_Feed_Run_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RSS Feed Run Config</label>
</CustomObject>

force-app/main/default/objects/RSS_Feed_Run_Config__c/fields/Last_Processed_Feed_Category__c.field-meta.xml
<CustomField>
    <fullName>Last_Processed_Feed_Category__c</fullName>
    <label>Last Processed Feed Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Run_Config__c/fields/Mailgun_API_Key__c.field-meta.xml
<CustomField>
    <fullName>Mailgun_API_Key__c</fullName>
    <label>Mailgun API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSS_Feed_Run_Config__c/fields/Mailgun_Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Mailgun_Endpoint_URL__c</fullName>
    <label>Mailgun Endpoint URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RSSFeedSendEmailQueable.cls
public class RSSFeedSendEmailQueable implements Queueable, Database.AllowsCallouts{
    List<Id> recordIds = new List<Id>();
    
    public RSSFeedSendEmailQueable(List<Id> ids){
        recordIds = ids;
    }
    public void execute(QueueableContext context) {
        List<RSS_Feed_Run_Config__c> rfrcList = [select id, name,Last_Processed_Feed_Category__c,SetupOwnerId,Mailgun_API_Key__c,Mailgun_Endpoint_URL__c from RSS_Feed_Run_Config__c WHERE SetupOwnerId = :UserInfo.getOrganizationId()];
        if(!(rfrcList.size() > 0) ){
            throw new RSSFeedException('No RSS Feed Run Config Found');
        }        
        RSS_Feed_Run_Config__c rfrc = rfrcList[0];
        //RSS_Feed_Config__mdt feedConfig = [SELECT Id, DeveloperName, Label, RSS_Feed_URL__c,To_Mail__c,From_Name_And_Email__c FROM RSS_Feed_Config__mdt WHERE DeveloperName = :rfrc.Last_Processed_Feed_Category__c];
        RSS_Feed_Config__mdt feedConfig = RSSFeedUtil.getFeedConfigByDeveloperName(rfrc.Last_Processed_Feed_Category__c);
        List<RSS_Feed_Entry__c> feeds = [SELECT Id, Name, Feed_Entry_Title__c, Feed_Entry_Description__c, Entry_GUID__c, Publication_Date_Time__c, Entry_Link__c, Feed_Category__c FROM RSS_Feed_Entry__c WHERE Id IN : recordIds];        
        String endpoint = rfrc.Mailgun_Endpoint_URL__c;
        String username = 'api';
        String password = rfrc.Mailgun_API_Key__c; // Replace with your actual token
        String authHeader = 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password));
        List<RSS_Feed_Entry__c> feedsToUpdate = new List<RSS_Feed_Entry__c>();
        for(RSS_Feed_Entry__c feed : feeds){
            String body = 'html=' + EncodingUtil.urlEncode(feed.Feed_Entry_Description__c, 'UTF-8') + '&subject='+ EncodingUtil.urlEncode(feed.Feed_Entry_Title__c, 'UTF-8')  + '&from=' + feedConfig.From_Name_And_Email__c; // Your form-urlencoded parameters
            HttpRequest request = new HttpRequest();
            request.setEndpoint(endpoint + '?to=' + feedConfig.To_Mail__c);
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            request.setHeader('Authorization', authHeader);
            request.setBody(body);
            
            // Perform the callout
            HttpResponse response = new Http().send(request);
            
            // Process the response
            if (response.getStatusCode() == 200) {
                // Successful response handling
                System.debug('Response Body: ' + response.getBody());
                feed.Email_Send_Status__c = 'Sent';
                feedsToUpdate.add(feed);
            } else {
                // Error handling
                System.debug('Error: ' + response.getStatusCode() + ' ' + response.getStatus());
                System.debug('Response Body: ' + response.getBody());
            }
            
        }
        if(feedsToUpdate.size() > 0) update feedsToUpdate;
    }
}